version: '3.5'

services:
  cfd-py-build:
    image: ghcr.io/cryptogarageinc/elements-testing:v0.2.2
    environment:
      CFD_SRC: /private/cfd-python
      CFD_WORK: /workspace/workdir
    working_dir: /private/cfd-python
    volumes:
      - .:/private/cfd-python
    working_dir: /private/cfd-python
    command: /bin/bash -c "./tools/build_for_docker.sh"

  cfd-py-integration-test:
    image: ghcr.io/cryptogarageinc/elements-testing:v0.2.2
    volumes:
      - ./integration_test:/private/cfd-python/integration_test
    working_dir: /private/cfd-python/integration_test
    entrypoint: /bin/bash -c "./test_entrypoint.sh"

  cfd-py-bitcoin-integration-test:
    image: ghcr.io/cryptogarageinc/elements-testing:v0.2.2
    volumes:
      - ./integration_test:/private/cfd-python/integration_test
    working_dir: /private/cfd-python/integration_test
    entrypoint: /bin/bash -c "./test_bitcoin_entrypoint.sh"

  cfd-py-test:
    image: ghcr.io/cryptogarageinc/elements-testing:v0.2.2
    environment:
      CFD_SRC: /private/cfd-python
      CFD_WORK: /workspace
    working_dir: /private/cfd-python
    volumes:
      - .:/private/cfd-python
    working_dir: /private/cfd-python
    command: /bin/bash -c "./tools/build_and_test_for_docker.sh"
